### ISSUE TITLE
Bug in get_potential_energy in eAtoms

### ISSUE THREAD

**Issue by sweitzner** [penghao-xiao/Electrochemical-barrier#6]
Hi Penghao,

There's a small bug in the `get_potential_energy` method of `eAtoms`. The potential shift shouldn't be included in the calculation of the enthalpy $H(r, N)$. I noticed this when I explicitly computed and printed the grand potential ( $\Omega(\mu_e)$ ) in the output and compared it to the enthalpy ( $H(N)$ ) that is computed in ECB (your enthalpy and the grand potential should agree after convergence is achieved). The derivation for this is below.

**The electronic grand potential:**
The grand potential is a function of the electronic chemical potential $\mu_e$ and is obtained as a Legendre transform of the DFT total energy:

$$\Omega(\mu_e) = E(N) - (N - N_0) \mu_e$$

where $\mu_e = E_F - \phi_{inner}$ ($E_F$ is the unaligned Fermi energy) and $\phi_{inner} = \lim_{z\to\infty} \phi(z)$ is the inner potential of the solvent (the potential shift obtained at the edge of the cell).

**Equivalence with the enthalpy at convergence:**
Let $U = \Phi^\prime - \Phi_{SHE}$ be the target electrode potential on the SHE scale and $\Phi^\prime = -\mu_e^\prime / e_0$ be the electrode potential on the solvent inner potential scale. Like $U$, $\Phi^\prime$ and $\mu_e^\prime$ are constants (target values determined by $U$ and the value used for $\Phi_{ref}$).

$$
\begin{split}
H(N)
&= E(N) - e_0 (N - N_0)  \phi \\
&= E(N) - e_0 (N - N_0)  \left[ -U + \frac{E_{fS}}{e_0} \right] \\
&= E(N) - e_0 (N - N_0) \Big[ -(\Phi^\prime - \Phi_{SHE}) - \Phi_{SHE} \Big] \\
&= E(N) + e_0 (N - N_0) \Phi^\prime \\
&= E(N) + e_0 (N - N_0) \left[ -\frac{\mu_e^\prime}{e_0} \right] \\
\Omega (\mu_e^\prime) &= E(N) - (N - N_0) \mu_e^\prime
\end{split}
$$

Hence, there is no need to subtract $\phi_{inner}$ in `get_potential_energy` since $e_0 \phi = \mu_e^\prime = E_F^\prime - \phi_{inner}$ and $\mu_e \to \mu_e^\prime$ at convergence.

Here's an example for $U = 0$ V/SHE, $E_{fS} = -4.6$ eV. Before making this fix, there is a large off-set between $\Omega$ and $H$ due to the additional $(N - N_0) \phi_{inner}$ term. 
```
mu_e        = -4.934189285459961
mu_e        = -4.9191370117693545
mu_e        = -4.890843679204176
mu_e        = -4.855014269268276
mu_e        = -4.82029941404733
mu_e        = -4.79231260704176
mu_e        = -4.770280772483752
mu_e        = -4.749616559625762
mu_e        = -4.726769181567085
mu_e        = -4.700457001387862
mu_e        = -4.671188126983612
mu_e        = -4.641457004697126
mu_e        = -4.6135886699049475
mu_e        = -4.588633786037732
```
```
Omega(mu_e) - H(N)  = -0.11963173068954802
Omega(mu_e) - H(N)  = -0.12477211525367693
Omega(mu_e) - H(N)  = -0.13511498768980346
Omega(mu_e) - H(N)  = -0.15019063135616761
Omega(mu_e) - H(N)  = -0.16856892732118922
Omega(mu_e) - H(N)  = -0.18873987509891776
Omega(mu_e) - H(N)  = -0.21013226868137735
Omega(mu_e) - H(N)  = -0.23322706679789462
Omega(mu_e) - H(N)  = -0.2583052615013912
Omega(mu_e) - H(N)  = -0.2852090739582991
Omega(mu_e) - H(N)  = -0.3133776161936339
Omega(mu_e) - H(N)  = -0.34201584732477386
Omega(mu_e) - H(N)  = -0.3697914595503562
Omega(mu_e) - H(N)  = -0.39595753054743454
```

And then after making that fix we can see the proper convergence as $\mu_e \to \mu_e^\prime$:
```
mu_e        = -4.895858327930022
mu_e        = -4.888349030857701
mu_e        = -4.874250098869652
mu_e        = -4.853133094712518
mu_e        = -4.82727003864974
mu_e        = -4.799566721097331
mu_e        = -4.7725757438033485
mu_e        = -4.7460940455149085
mu_e        = -4.718254436295294
mu_e        = -4.688918541159515
mu_e        = -4.660204774305972
mu_e        = -4.633242878245954
mu_e        = -4.605992152651608
mu_e        = -4.577698962756334
```

```
Omega(mu_e) - H(N)  = 0.035502999351592734
Omega(mu_e) - H(N)  = 0.03546693079556462
Omega(mu_e) - H(N)  = 0.03535083774431769
Omega(mu_e) - H(N)  = 0.034831113832410665
Omega(mu_e) - H(N)  = 0.0338177817510541
Omega(mu_e) - H(N)  = 0.032409635506269296
Omega(mu_e) - H(N)  = 0.03066670967382379
Omega(mu_e) - H(N)  = 0.02840068244813665
Omega(mu_e) - H(N)  = 0.0250581150509106
Omega(mu_e) - H(N)  = 0.02042458890434773
Omega(mu_e) - H(N)  = 0.014882620208481967
Omega(mu_e) - H(N)  = 0.008779444144806803
Omega(mu_e) - H(N)  = 0.0016778027423924868
Omega(mu_e) - H(N)  = -0.006567655468302291
```

**Comment by penghao-xiao** [comment]
Hi Steve,

Thank you for the comments, which unified many terminologies.
The  potential shift is there to compensate the shift from the background charge that is put in the centre of the electrolyte (edge of the box in our code). It is an artificial thing due to the periodic boundary condition, not a physical property. For DFT codes allowing infinite boundary in the slab norm direction, this potential shift will be gone. For VASPsol, it should be there. 

See the last paragraph here: 
https://github.com/henniggroup/VASPsol/blob/master/docs/USAGE.md

**Comment by sweitzner** [comment]
Hi Penghao, thanks for pointing to their documentation. I think I’m confused because I account for the potential shift when I compute $\mu_e$. The corrective term is included in my grand potential calculation. It seems like the corrective term is being double counted in $H$.

**Comment by penghao-xiao** [comment]
Yes, E(N) from VASPsol needs that correction, which stems from a numerical issue rather than physics. For the record, the energy correction and the dependence on supercell size have been well documented in the following paper and its addition:
 https://pubs.acs.org/doi/abs/10.1021/acs.jpcc.8b10046 

You are more than welcome to contribute!

**Comment by sweitzner** [comment]
Great! Thanks. I'll close this issue for now.
